import React, { useEffect, useState } from 'react';
import { Search, RefreshCw, UserRoundCog, XCircle, Eye, X } from 'lucide-react';
import toast from 'react-hot-toast';
import jobAPI from '../../api/jobs';
import workerAPI from '../../api/workers';
import Loader from '../../components/Common/Loader';

const money = (v) => `₹${Number(v || 0).toLocaleString('en-IN')}`;
const statusClass = { pending:'bg-amber-50 text-amber-700', assigned:'bg-blue-50 text-blue-700', accepted:'bg-indigo-50 text-indigo-700', arrived:'bg-violet-50 text-violet-700', in_progress:'bg-cyan-50 text-cyan-700', completed:'bg-emerald-50 text-emerald-700', cancelled:'bg-rose-50 text-rose-700' };
const unwrap = (r) => r?.data?.data || r?.data || {};
export default function JobsList(){
 const [jobs,setJobs]=useState([]),[workers,setWorkers]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[filters,setFilters]=useState({status:'',workerId:'',bookingId:'',fromDate:'',toDate:'',page:1,limit:10}),[meta,setMeta]=useState({}),[selected,setSelected]=useState(null),[newWorker,setNewWorker]=useState('');
 const load=async()=>{try{setLoading(true);const [j,w]=await Promise.all([jobAPI.getAll(filters),workerAPI.getAll({limit:100})]);const d=unwrap(j);setJobs(d.rows||d.items||[]);setMeta(d);const wd=unwrap(w);setWorkers(wd.rows||wd.items||[]);}catch(e){toast.error(e.response?.data?.error||'Failed to load jobs')}finally{setLoading(false)}};
 useEffect(()=>{load()},[filters.page,filters.status,filters.workerId,filters.bookingId,filters.fromDate,filters.toDate]);
 const act=async(fn,msg)=>{try{setBusy(true);await fn();toast.success(msg);setSelected(null);await load()}catch(e){toast.error(e.response?.data?.error||'Action failed')}finally{setBusy(false)}};
 if(loading&&!jobs.length)return <Loader/>;
 return <div className="space-y-6">
  <div className="flex flex-col lg:flex-row lg:items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-orange-500">Operations</p><h1 className="text-3xl font-black text-slate-900">Jobs & Assignments</h1><p className="text-slate-500 mt-1">Monitor every job and control worker assignment in real time.</p></div><button onClick={load} className="btn-secondary"><RefreshCw size={16}/> Refresh</button></div>
  <div className="card grid grid-cols-1 md:grid-cols-2 xl:grid-cols-6 gap-3"><input className="input xl:col-span-2" placeholder="Booking ID" value={filters.bookingId} onChange={e=>setFilters({...filters,bookingId:e.target.value,page:1})}/><select className="input" value={filters.status} onChange={e=>setFilters({...filters,status:e.target.value,page:1})}><option value="">All statuses</option>{['pending','assigned','accepted','arrived','in_progress','completed','cancelled'].map(x=><option key={x}>{x}</option>)}</select><select className="input" value={filters.workerId} onChange={e=>setFilters({...filters,workerId:e.target.value,page:1})}><option value="">All workers</option>{workers.map(w=><option key={w.id} value={w.id}>{w.User?.name||w.name||`Worker #${w.id}`}</option>)}</select><input type="date" className="input" value={filters.fromDate} onChange={e=>setFilters({...filters,fromDate:e.target.value,page:1})}/><input type="date" className="input" value={filters.toDate} onChange={e=>setFilters({...filters,toDate:e.target.value,page:1})}/></div>
  <div className="card overflow-hidden"><div className="overflow-x-auto"><table className="table"><thead><tr><th>Job</th><th>Customer</th><th>Worker</th><th>Service</th><th>Amount</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody>{jobs.map(j=><tr key={j.id}><td className="font-bold">#{j.id}<div className="text-xs text-slate-400">Booking #{j.bookingId}</div></td><td>{j.Booking?.User?.name||'—'}<div className="text-xs text-slate-400">{j.Booking?.User?.mobile||''}</div></td><td>{j.Worker?.User?.name||'Unassigned'}</td><td>{j.Booking?.Service?.name||'—'}</td><td>{money(j.Booking?.totalAmount)}</td><td><span className={`badge ${statusClass[j.status]||'bg-slate-100 text-slate-600'}`}>{j.status}</span></td><td>{j.createdAt?new Date(j.createdAt).toLocaleDateString('en-IN'):'—'}</td><td><button className="icon-btn" onClick={()=>{setSelected(j);setNewWorker(j.workerId||'')}}><Eye size={17}/></button></td></tr>)}{!jobs.length&&<tr><td colSpan="8" className="text-center py-12 text-slate-400">No jobs found</td></tr>}</tbody></table></div></div>
  {selected&&<div className="modal-backdrop"><div className="modal max-w-2xl"><div className="flex justify-between items-start"><div><p className="eyebrow">Job #{selected.id}</p><h2 className="modal-title">Assignment Control</h2></div><button className="icon-btn" onClick={()=>setSelected(null)}><X/></button></div><div className="grid grid-cols-2 gap-4 mt-6"><div className="soft"><span>Customer</span><b>{selected.Booking?.User?.name||'—'}</b></div><div className="soft"><span>Service</span><b>{selected.Booking?.Service?.name||'—'}</b></div><div className="soft"><span>Current Worker</span><b>{selected.Worker?.User?.name||'Unassigned'}</b></div><div className="soft"><span>Booking Amount</span><b>{money(selected.Booking?.totalAmount)}</b></div></div><div className="mt-6"><label className="label">Assign / Reassign Verified Worker</label><select className="input" value={newWorker} onChange={e=>setNewWorker(e.target.value)}><option value="">Select worker</option>{workers.filter(w=>w.isVerified).map(w=><option key={w.id} value={w.id}>{w.User?.name||w.name} · {w.profession||'Worker'}</option>)}</select></div><div className="flex justify-end gap-3 mt-6"><button className="btn-secondary" onClick={()=>setSelected(null)}>Close</button>{!['completed','cancelled'].includes(selected.status)&&<><button disabled={busy||!newWorker} className="btn-primary" onClick={()=>act(()=>jobAPI.reassign(selected.id,newWorker),'Worker reassigned') }><UserRoundCog size={16}/> Reassign</button><button disabled={busy} className="btn-danger" onClick={()=>act(()=>jobAPI.cancel(selected.id,{reason:'Cancelled by admin'}),'Job cancelled')}><XCircle size={16}/> Cancel Job</button></>}</div></div></div>}
 </div>
}
